_id: "443610478048968704"
name: Mock 0
description: Mock 0 is an AI-based code tool that can help you generate code quickly.
model: ""
createdAt: 2024-05-09T03:09:39.851Z
updatedAt: 2024-05-29T09:20:36.091Z
createdBy: z1TCComgCJNHbHWetTWGdhPB6NYZ2ReDjLu
updatedBy: z1TCComgCJNHbHWetTWGdhPB6NYZ2ReDjLu
pinnedAt: null
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
