_id: "443610478048968704"
name: mock-0
description: null
model: ""
createdAt: 2024-05-09T03:09:39.851Z
updatedAt: 2024-05-29T16:13:01.071Z
createdBy: z1oHa79x3H6vxv9hfW8bHczPmwHKfAaRRmS
updatedBy: z1oHa79x3H6vxv9hfW8bHczPmwHKfAaRRmS
pinnedAt: null
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
