_id: "443610478048968704"
name: v0
model: ""
createdAt: 2024-05-09T03:09:39.851Z
updatedAt: 2024-05-09T03:09:39.851Z
createdBy: z1TCComgCJNHbHWetTWGdhPB6NYZ2ReDjLu
updatedBy: z1TCComgCJNHbHWetTWGdhPB6NYZ2ReDjLu
gitType: simple
temperature: 1
topP: 1
