_id: "443610478048968704"
name: v0
description: null
model: ""
createdAt: 2024-05-09T03:09:39.851Z
updatedAt: 2024-05-29T03:43:57.231Z
createdBy: z1TCComgCJNHbHWetTWGdhPB6NYZ2ReDjLu
updatedBy: z1TCComgCJNHbHWetTWGdhPB6NYZ2ReDjLu
pinnedAt: null
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: null
