id: "443610478048968704"
name: Mock0
description: AI-Powered Components generator, Inspired by Vercel's V0
createdAt: 2024-05-09T03:09:39.851Z
updatedAt: 2024-06-21T03:17:20.854Z
createdBy: z1e32Au8HZgwiNMntL1vL9ZWfRNcRdUKZDD
updatedBy: z1e32Au8HZgwiNMntL1vL9ZWfRNcRdUKZDD
temperature: 1
topP: 1
