_id: "443610478048968704"
name: Mock 0
description: null
model: ""
createdAt: 2024-05-09T03:09:39.851Z
updatedAt: 2024-06-04T07:39:13.561Z
createdBy: z1oHa79x3H6vxv9hfW8bHczPmwHKfAaRRmS
updatedBy: z1U5GTVaSjnar3nLsE9WapbERRRAx45LJoq
pinnedAt: null
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
