variables:
  - key: designed-components
    scope: session
    type:
      type: object
    reset: true
    defaultValue: ""
  - key: component-code
    scope: session
    type:
      type: string
      id: iKSVRDXtoSDV7RqvqJtcRmOGPysUwGsH
    reset: true
    defaultValue: ""
